- name: Update apt-get
  apt:
    update_cache: yes
  become: true

- name: Install required package for docker
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
  become: true

- name: Add docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  become: true

- name: Add docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    state: present
    update_cache: true
  become: true

- name: Install docker
  package:
    name:
      - "docker-ce-{{ docker.version }}"
      - "docker-ce-cli-{{ docker.version }}"
      - containerd.io
    state: present
  become: true
